# Generated by Django 4.2.30 on 2026-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('DISABLED', 'Nogironlar')], default='STANDARD', max_length=15),
        ),
    ]
