# Generated by Django 4.2.30 on 2026-06-25 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingspot_spot_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard_name', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='is_lost_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='session_type',
            field=models.CharField(choices=[('PAID', 'Standard'), ('SUBSCRIBED', 'Abonement')], default='PAID', max_length=15),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('VIP', 'VIP'), ('DISABLED', 'Nogironlar'), ('RESERVED', 'Rezervlangan')], default='STANDARD', max_length=15),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='parking.parkingshift'),
        ),
    ]
