# Generated by Django 4.2.30 on 2026-06-26 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parkingshift_parkingsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TELEGRAM', 'Telegram Bot'), ('SMS', 'SMS Gateway')], max_length=15)),
                ('recipient', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-sent_time'],
            },
        ),
    ]
